<?php

$helper = Mage::helper('tealium_tags');
$store = Mage::app()->getStore();

if (!$helper->isEnabled($store)) {
    return; // not enabled, no javascript inserted
}

$ids = array();
$skus = array();
$names = array();

foreach($this->getItems() as $item) {
    $ids[] = $item->getProductId();
    $skus[] = $item->getSku();
    $names[] = $item->getName();
}
		
$customData = array();
$customData["page_type"] = "product compare";
$customData["product_id"] = implode('","', $ids);
$customData["product_sku"] = implode('","', $skus);
$customData["product_name"] = implode('","', $names);

$tealium = $helper->init($store, $this, "Home")->
			addCustomDataFromSetup($store, "Home")->
			addCustomDataFromObject($customData)->
			getTealiumObject();

if ($helper->getIsExternalScript($store)){
	$syncType = "sync";
	$externalScriptType = $helper->getExternalScriptType($store);
	if ($externalScriptType == "sync" || $externalScriptType == "async"){
		$syncType = $externalScriptType;
	}
	echo $tealium->render("full", true, $syncType);
}
else {
	echo $tealium->render("udo");
}


echo $helper->getDiagnosticTag($store);
?>