<?php

$helper = Mage::helper('tealium_tags');
$store = Mage::app()->getStore();

if (!$helper->isEnabled($store)) {
    return; // not enabled, no javascript inserted
}

$tealium = $helper->getTealiumObject($store, $this);
if(preg_match('/checkout.+success|success.+checkout/i',$_SERVER['PHP_SELF'])){
	$tealium = $helper->init($store, $this, "Confirmation")->
				addCustomDataFromSetup($store, "Confirmation")->
				getTealiumObject();
}
else{
	$customData = array();
	$customData["page_type"] = "generic";
	$tealium = $helper->init($store, $this, "Home")->
				addCustomDataFromSetup($store, "Home")->
				addCustomDataFromObject($customData)->
				getTealiumObject();

}

if ($helper->getIsExternalScript($store)){
	$syncType = "sync";
	$externalScriptType = $helper->getExternalScriptType($store);
	if ($externalScriptType == "sync" || $externalScriptType == "async"){
		$syncType = $externalScriptType;
	}
	echo $tealium->render("full", true, $syncType);
}
else {
	echo $tealium->render("udo");
}

echo $helper->getDiagnosticTag($store);
?>
