<?php

$helper = Mage::helper('tealium_tags');
$store = Mage::app()->getStore();

if (!$helper->isEnabled($store)) {
    return; // not enabled, no javascript inserted
}

$_product_id = $this->getProductId();
$_category_id = $this->getCategoryId();
$_product = Mage::getModel('catalog/product')->load($_product_id);
$_category = Mage::getModel('catalog/category')->load($_category_id);

$customData = array();
$customData["page_name"] = $_product->getName();
$customData["page_type"] = "product send";
$customData["product_id"] = $_product->getId();
$customData["product_sku"] = $_product->getSku();
$customData["product_name"] = $_product->getName();
$customData["product_brand"] = $_product->getBrand();
$customData["product_category"] = $_category ? $_category->getName() : 'no_category';
$customData["product_unit_price"] = number_format($_product->getSpecialPrice()?:"",2,"");
$customData["product_list_price"] = number_format($_product->getPrice()?:"",2,"");

$tealium = $helper->init($store, $this, "ProductPage")->
			addCustomDataFromSetup($store, "Home")->
			addCustomDataFromObject($customData)->
			getTealiumObject();

if ($helper->getIsExternalScript($store)){
	$syncType = "sync";
	$externalScriptType = $helper->getExternalScriptType($store);
	if ($externalScriptType == "sync" || $externalScriptType == "async"){
		$syncType = $externalScriptType;
	}
	echo $tealium->render("full", true, $syncType);
}
else {
	echo $tealium->render("udo");
}

echo $helper->getDiagnosticTag($store);
?>