<?php

$helper = Mage::helper('tealium_tags');
$store = Mage::app()->getStore();

if (!$helper->isEnabled($store)) {
    return; // not enabled, no javascript inserted
}

$tealium = $helper->init($store, $this, "Home")->
			addCustomDataFromSetup($store, "Home")->
			getTealiumObject();

if ($helper->getIsExternalScript($store)){
	$syncType = "sync";
	$externalScriptType = $helper->getExternalScriptType($store);
	if ($externalScriptType == "sync" || $externalScriptType == "async"){
		$syncType = $externalScriptType;
	}
	echo $tealium->render("full", true, $syncType);
}
else {
	echo $tealium->render("udo");
}

echo $helper->getDiagnosticTag($store);
?>