<?php

$helper = Mage::helper('tealium_tags');
$store = Mage::app()->getStore();

if (!$helper->isEnabled($store)) {
    return; // not enabled, no javascript inserted
}

$tags = array();

if( sizeof($this->getTags()) > 0 ) {
    foreach ($this->getTags()as $name => $tag) {
        $tags[] = $name;
    }
} else {
    $tags[] = "no-tags";
}

$customData = array();
$customData["page_type"] = "tag list";
$customData["page_name"] = $this->getLayout()->getBlock('head')->getTitle();
$customData["search_keyword"] = implode('","', $tags);

$tealium = $helper->init($store, $this, "Search")->
			addCustomDataFromSetup($store, "Search")->
			addCustomDataFromObject($customData)->
			getTealiumObject();

if ($helper->getIsExternalScript($store)){
	$syncType = "sync";
	$externalScriptType = $helper->getExternalScriptType($store);
	if ($externalScriptType == "sync" || $externalScriptType == "async"){
		$syncType = $externalScriptType;
	}
	echo $tealium->render("full", true, $syncType);
}
else {
	echo $tealium->render("udo");
}

echo $helper->getDiagnosticTag($store);
?>